### ISSUE TITLE
As a researcher, I would like a standardized test schema to easily track each test

### ISSUE THREAD

**Issue by KjetilIN** [RIT-NTNU-Bachelor/Bachelor#1]
- [x] Create the standardized testing schema for face tracking
- [ ] Create the standardized testing schema for MVP tests
- [ ] Create the standardized testing schema for prototype tests
- [x] Create the standardized testing schema for test facilitators

**Comment by haugeSander** [comment]
# Test facilitator results
We will not create webcam based light detection software as webcams differ widely and webcams automatically adjust to environment, making the data gathered very unpredictable. Instead, we will use UPRtek premium, a handheld spectrometer which we may use while at Munsell Color lab during tests.
