### ISSUE TITLE
Logistics: get camera and place to work with UE

### ISSUE THREAD

**Issue by KjetilIN** [RIT-NTNU-Bachelor/Bachelor#10]
# What?
Get a camera for the prototype, to be used for face tracking. Also, as our laptops are too weak for UE and VS, we need to find alternatives to work on.

## Sub-issues
- [x] Follow-up Murdoch on the camera business.
- [x] Ask Shaun or Jennifer about workstations.

**Comment by haugeSander** [comment]
### Update 05.03
Sent message to both Micheal and Shaun for these questions. Will update as soon as I get any replies.

**Comment by haugeSander** [comment]
### Update 19.03
Response from Shaun:
* In terms of powerful workstations, he recommended visiting [RIT ITS helpdesk](https://www.rit.edu/its/)
* In terms of helping point you in a direction for your (and Michaels) R&D - I'm a bit overwhelmed by my own research at the moment.  I do think it could work based on a 1-person perspective rendering shift based on face tracking.

Looks like we are on our own.
