### ISSUE TITLE
Submit test form RIT

### ISSUE THREAD

**Issue by haugeSander** [RIT-NTNU-Bachelor/Bachelor#14]
# What
We need to submit a test form and have it approved to perform user tests on campus.

Susan will send us a mail about the process.

**Comment by haugeSander** [comment]
# Update evening 02.04
Started doing the course, unsure if it is mandatory.
Received the form we need to submit and they require a lot of information to be filled in. Asked Micheal for help.

## Links
[How to submit](https://www.rit.edu/hsro/how-submit)
[The course](https://www.rit.edu/hsro/training)

**Comment by KjetilIN** [comment]
Let us know when the form has been submitted @haugeSander !

**Comment by marhjoh** [comment]
Sander has submitted and done. Kjetil and Martin will proceed and finish the course.
