### ISSUE TITLE
Research: .exe project of UE

### ISSUE THREAD

**Issue by KjetilIN** [RIT-NTNU-Bachelor/Bachelor#9]
# What?
Research if an .exe file will improve the performance of the simulation. As of development it is very computationally heavy to run both Unreal Engine, Visual Studio and face tracking in parallel. Should research if an executable will solve this, and if not address the problem.

## Sub-issues
- [ ] Figure out possible performance improvements. Add all findings in this issue.
- [ ] Try to create an .exe file from a test UE project.

**Comment by haugeSander** [comment]
## Sprint 4 meeting
Make into thesis work: further work.

**Comment by haugeSander** [comment]
# Sprint 5 meeting

Look into this, and prebuilding lighting.

**Comment by haugeSander** [comment]
# Findings

To get an .exe of the project, the following must be done:

- Build in shipping.
![Image](https://github.com/RIT-NTNU-Bachelor/Bachelor/assets/98831002/6223c3dd-00ca-4e22-b890-c50fd7b5a473)
- Build lighting: Build->Lighting build. Select medium preset quality.
- Package game into a chosen OS.
> To package a project for a specific platform, click on File > Package Project > [PlatformName] in the Editor's main menu.

The built project will be found in Build/OS_TYPE.

Good source: [YouTube video](https://www.youtube.com/watch?v=O2PKihXmejw)

**Comment by haugeSander** [comment]
# Idea
Show performance boost gains as graphs.

**Comment by haugeSander** [comment]
# Solved
The application is now built, and menu works pretty well with it.
Some performance issues it seems, but might be that the graphics is at max.

**Comment by haugeSander** [comment]
# Fix
Removed bloom and motion blur, which improved it considerably!
